# Generated by Django 2.0.5 on 2018-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Turkey', max_length=100),
            preserve_default=False,
        ),
    ]
