# Generated by Django 2.0.2 on 2018-03-26 14:31

import campowner.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=campowner.models.campowner_upload_location, width_field='width_field')),
                ('width_field', models.PositiveIntegerField(default=0)),
                ('height_field', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
