# Generated by Django 2.0.3 on 2018-05-15 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campowner',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campowner',
            name='phone_number',
            field=models.CharField(default='32232323', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campowner',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campowner',
            name='web_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
