# Generated by Django 2.0.3 on 2018-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campowner',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
