# Generated by Django 2.0.2 on 2018-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campowner',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kamp Alanı Adı'),
        ),
    ]
