# Generated by Django 2.0.2 on 2018-05-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campowner', '0002_auto_20180522_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campowner.CampOwner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
