# Generated by Django 2.0.5 on 2018-05-15 12:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0003_auto_20180515_1557'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reservation',
            name='intensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camps.campLocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='tenttype',
            field=models.IntegerField(default=0),
        ),
    ]
