# Generated by Django 2.0.5 on 2018-05-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180515_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='tenttype',
            new_name='tents',
        ),
    ]
