# Generated by Django 2.0.3 on 2018-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
